version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      target: builder
    # Override production command to run in dev mode
    command: /bin/sh -c "npx prisma generate && npx prisma db push && npm run dev"
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/inventory_db
      - NODE_ENV=development
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
      - ./public/uploads:/app/public/uploads
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=inventory_db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
